name: Iteracao
on:
  push:
    branches:
      - 'Iteracao**'
      
jobs:
  tests:
    name: Executar os testes unitários
    runs-on: ubuntu-latest
    env:
      CUCUMBER_PUBLISH_ENABLED: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install RubyGems
        run: bundle install

      - name: Migrate database
        run: bundle exec rails db:migrate

      - name: Run rspec tests
        run: bundle exec rspec

      - name: Run cucumber tests
        run: bundle exec cucumber --guess

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}