name: Iteracao
on:
  push:
    branches:
      - 'Iteracao**'
      
jobs:
  tests:
    name: Executar os testes unitários
    runs-on: ubuntu-latest
    env:
      CUCUMBER_PUBLISH_ENABLED: false
      CUCUMBER_PUBLISH_QUIET: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install RubyGems
        run: bundle install

      - name: Migrate database
        run: bundle exec rails db:migrate

      - name: Run rspec and cucumber tests
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          bundle exec rspec
          bundle exec cucumber --guess

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}